name: Run Code Tests

on:
  push:
    paths:
      - "solutions/**"
  pull_request:
    paths:
      - "tests/**"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Ensure previous commit is available

      - name: Detect Changed Files
        id: changed-files
        run: |
          BEFORE_COMMIT="${{ github.event.before }}"
          if [ -z "$BEFORE_COMMIT" ] || ! git cat-file -e "$BEFORE_COMMIT"^{commit}; then
            BEFORE_COMMIT=$(git rev-parse HEAD~1)  # Use last commit as fallback
          fi
          
          CHANGED_FILES=$(git diff --name-only "$BEFORE_COMMIT" HEAD | grep '^solutions/')
          echo "Detected changed files: $CHANGED_FILES"
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No file changes detected. Exiting..."
            exit 1
          fi

          echo "CHANGED_FILES=$(echo "$CHANGED_FILES" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Determine File Type
        id: determine-file
        run: |
          for file in $CHANGED_FILES; do
            case "$file" in
              *.c) echo "LANGUAGE=C" >> $GITHUB_ENV ;;
              *.cpp) echo "LANGUAGE=C++" >> $GITHUB_ENV ;;
              *.py) echo "LANGUAGE=Python" >> $GITHUB_ENV ;;
              *.java) echo "LANGUAGE=Java" >> $GITHUB_ENV ;;
            esac
          done

      - name: Install Java Dependencies
        if: env.LANGUAGE == 'Java'
        run: sudo apt update && sudo apt install -y openjdk-17-jdk

      - name: Compile and Run Java Tests
        if: env.LANGUAGE == 'Java'
        run: |
          echo "Compiling Java files..."
          mkdir -p bin  # Ensure the bin directory exists
          javac -d bin solutions/Solution.java tests/Test.java 2>&1 | tee test_results.log  # ✅ Redirect errors

          if [ $? -eq 0 ]; then
            echo "Running Java Test Cases..."
            java -cp bin tests.Test | tee -a test_results.log  # ✅ Append output to log
          else
            echo "Java compilation failed." | tee -a test_results.log  # ✅ Log failure
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.log
          if-no-files-found: ignore  # ✅ Avoid warnings
          compression-level: 6
          overwrite: false
          include-hidden-files: false
