name: Run Tests Based on Submitted Language

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-solutions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [c, cpp, java, py]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        if: matrix.language == 'py'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Java
        if: matrix.language == 'java'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up C/C++ Compiler
        if: matrix.language == 'c' || matrix.language == 'cpp'
        run: sudo apt update && sudo apt install -y gcc g++

      - name: Run Python Tests
        if: matrix.language == 'py'
        run: python tests/test.py

      - name: Compile and Run C Tests
        if: matrix.language == 'c'
        run: |
          gcc solutions/solution.c -o solution_c
          ./solution_c < tests/test.c

      - name: Compile and Run C++ Tests
        if: matrix.language == 'cpp'
        run: |
          g++ solutions/solution.cpp -o solution_cpp
          ./solution_cpp < tests/test.cpp

      - name: Compile and Run Java Tests
        if: matrix.language == 'java'
        run: |
          javac solutions/solution.java tests/test.java
          java tests.test
