name: Run Tests Based on Language

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect Submitted File
        id: detect-file
        run: |
          if [ -f solutions/solution.cpp ]; then
            echo "language=cpp" >> $GITHUB_ENV
          elif [ -f solutions/solution.c ]; then
            echo "language=c" >> $GITHUB_ENV
          elif [ -f solutions/solution.py ]; then
            echo "language=python" >> $GITHUB_ENV
          else
            echo "No solution file found!"
            exit 1
          fi

      - name: Run C++ Tests
        if: env.language == 'cpp'
        run: |
          g++ solutions/solution.cpp -o solution_cpp
          g++ tests/test.cpp -o test_cpp
          ./test_cpp

      - name: Run C Tests
        if: env.language == 'c'
        run: |
          gcc solutions/solution.c -o solution_c
          gcc tests/test.c -o test_c
          ./test_c

      - name: Run Python Tests
        if: env.language == 'python'
        run: |
          python3 tests/test.py
